<a href="https://colab.research.google.com/github/quickish007/End-to-end-PyTorch-training-pipeline/blob/main/pytorch_training_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [48]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [49]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [50]:
df.shape

(569, 33)

In [51]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [52]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

### train test split

In [53]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### scaling

In [54]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [55]:
X_train

array([[-0.87743273, -1.02922167, -0.90578183, ..., -1.0881287 ,
        -1.65579561, -0.58468712],
       [ 1.06129235,  0.30232824,  1.0471198 , ...,  0.50332859,
         0.61588208, -0.40961359],
       [-0.56130584, -0.2758148 , -0.57752901, ..., -0.40803031,
         0.56031102, -0.49658922],
       ...,
       [-0.2200007 ,  0.09064594, -0.27237547, ...,  0.00862956,
        -0.0021355 , -0.5521414 ],
       [-1.04528772, -0.96776552, -1.01600993, ..., -0.33570501,
         0.22688464,  0.72443639],
       [ 0.23041017, -0.56716247,  0.24999229, ..., -0.20488795,
        -1.19270342,  0.10887339]])

In [56]:
y_train

173    B
492    M
367    B
289    B
130    B
      ..
100    M
343    M
171    M
426    B
500    B
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [57]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [58]:
y_train

array([0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,

### Numpy arrays to PyTorch tensors

In [59]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [60]:
X_train_tensor.type()

'torch.FloatTensor'

In [61]:
y_train_tensor.shape

torch.Size([455])

### Defining the model

In [62]:
import torch.nn as nn

class MySimpleNN(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out





### Important Parameters

In [63]:
learning_rate = 0.1
epochs = 25

In [64]:
loss_function = nn.BCELoss()
type(loss_function)

torch.nn.modules.loss.BCELoss

### Training Pipeline

In [65]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

#Define Optimizer

optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)


# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  # loss calculate
  loss = loss_function(y_pred, y_train_tensor.view(-1, 1))

  #clear gradient
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameters update
  optimizer.step()


  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.7857533693313599
Epoch: 2, Loss: 0.5640091300010681
Epoch: 3, Loss: 0.45468685030937195
Epoch: 4, Loss: 0.3923247754573822
Epoch: 5, Loss: 0.35128238797187805
Epoch: 6, Loss: 0.321755975484848
Epoch: 7, Loss: 0.2992359399795532
Epoch: 8, Loss: 0.2813383638858795
Epoch: 9, Loss: 0.2666739523410797
Epoch: 10, Loss: 0.25437337160110474
Epoch: 11, Loss: 0.24386197328567505
Epoch: 12, Loss: 0.23474319279193878
Epoch: 13, Loss: 0.22673358023166656
Epoch: 14, Loss: 0.21962447464466095
Epoch: 15, Loss: 0.21325841546058655
Epoch: 16, Loss: 0.2075141817331314
Epoch: 17, Loss: 0.20229659974575043
Epoch: 18, Loss: 0.19752976298332214
Epoch: 19, Loss: 0.19315235316753387
Epoch: 20, Loss: 0.18911413848400116
Epoch: 21, Loss: 0.18537355959415436
Epoch: 22, Loss: 0.18189579248428345
Epoch: 23, Loss: 0.17865155637264252
Epoch: 24, Loss: 0.17561592161655426
Epoch: 25, Loss: 0.1727674901485443


In [66]:
model.linear.weight

Parameter containing:
tensor([[ 0.2551,  0.1258,  0.2682,  0.2003,  0.1539,  0.1726,  0.2422,  0.1005,
          0.2023, -0.1613,  0.0621,  0.0475,  0.2095,  0.0497,  0.0504,  0.0713,
         -0.1055, -0.0252, -0.0442,  0.0639,  0.1995,  0.2239,  0.4307,  0.4100,
          0.2000,  0.1763,  0.1874,  0.1891,  0.1328, -0.0383]],
       requires_grad=True)

### Evaluation

In [67]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.5526315569877625
